experiment:
  max_cost: 1.0
  enable_autoprompt: False

planner:
  max_rounds: 30
  model: gpt-4o-2024-11-20
  temperature: 1.0
  max_tokens: 4096
  prompt: prompts/rev_planner_prompt.yaml
  toolset:
    - run_command
    - submit_flag
    - giveup
    - delegate
executor:
  max_rounds: 100
  model: gpt-4o-2024-11-20
  temperature: 1.0
  max_tokens: 4096
  len_observations: 5
  prompt: prompts/rev_executor_prompt.yaml
  toolset:
    - run_command
    - finish_task
    - disassemble
    - decompile
    - create_file
autoprompter:
  max_rounds: 5
  model: gpt-4o-2024-11-20
  temperature: 1.0
  max_tokens: 4096
  prompt: prompts/autoprompt_prompt.yaml
  toolset:
    - run_command
    - generate_prompt
